replicaCount: 1
appName: dev-sandbox
hostname: dev.sethsandbox.com
environment: dev
image:
  repository: ghcr.io/ra535i/sandbox-app
  tag: "b849a8934e36246238ab3eb9228c798bb4665590"
  pullPolicy: Always
