replicaCount: 1
appName: dev-sandbox
hostname: dev.sethsandbox.com
environment: dev
image:
  repository: ghcr.io/ra535i/sandbox-app
  tag: "4fcd64e2cef2271b67f2cea4e19fc8e67cb433a5"
  pullPolicy: Always
