replicaCount: 1
appName: dev-sandbox
hostname: dev.sethsandbox.com
environment: dev
image:
  repository: ghcr.io/ra535i/sandbox-app
  tag: "276de625c76d642b317b59ba387699657ed01f5e"
  pullPolicy: Always
